### ISSUE TITLE
first line in tab-separated values (with column names) is not tab-separated

### ISSUE THREAD

**Issue by agricolamz** [clld/sails#3]
This problem complicate reading of the files. I'll try to figure out my own solution, but I would like to know if there will be some changes. Probably this issue is somehow related to [issue #47 in clld/wals3](https://github.com/clld/wals3/issues/47).

**Comment by xrotwang** [comment]
I believe the csv reader in R has an argument to specify a number of lines
to skip.
Am 12.08.2017 14:20 schrieb "George Moroz" <notifications@github.com>:

**Comment by agricolamz** [comment]
Yes, Robert, it does. It is not a problem for me, I just try to report strange behavior I found.

**Comment by xrotwang** [comment]
It actually is a bug. [This line](https://github.com/clld/sails/blob/a834da1a9cf34155d42d2e2138c2869a8638a747/sails/templates/parameter/detail_tab.mako#L1) should be tab rather than space separated. Thanks for catching it @agricolamz !
I thought the issue was due to included citation info as is the case [for WALS](http://wals.info/feature/1A.tab).

**Comment by xrotwang** [comment]
The fixed version is deployed, see e.g. http://sails.clld.org/parameters/AND1.tab

**Comment by agricolamz** [comment]
I see! Sorry for vague description.
